# Generated by Django 3.1.7 on 2021-04-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_repari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='test',
            new_name='test1',
        ),
    ]
