# Generated by Django 3.1.7 on 2021-04-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210425_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='test1',
            new_name='test',
        ),
    ]
