# Generated by Django 3.1.7 on 2021-03-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210327_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_technology',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
