# Generated by Django 3.1.7 on 2021-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
