# Generated by Django 3.1.7 on 2021-04-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_complete1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete1',
        ),
    ]
