# Generated by Django 3.1.7 on 2021-05-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_complete1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer'),
        ),
    ]
