# Generated by Django 3.1.7 on 2021-05-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210503_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='username',
            new_name='customer',
        ),
    ]
