# Generated by Django 3.1.7 on 2021-05-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210503_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='customer',
            new_name='username',
        ),
    ]
