# Generated by Django 3.1.7 on 2021-05-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210503_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
