# Generated by Django 3.1.7 on 2021-05-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210503_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='pay_id',
        ),
    ]
