# Generated by Django 3.1 on 2021-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210601_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
