# Generated by Django 3.1 on 2021-06-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_shippingaddress_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ShippingAddresses',
        ),
    ]
